apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam-token-service.fullname" . }}-server
  labels:
    {{- include "iam-token-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "iam-token-service.componentSelectorLabels" (dict "component" "server" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam-token-service.fullname" . }}-consumer
  labels:
    {{- include "iam-token-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "iam-token-service.componentSelectorLabels" (dict "component" "consumer" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
