// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "BCBP Solutions IAM Team",
            "email": "platform@bcbpsolutions.com"
        },
        "license": {
            "name": "Proprietary"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tenants/{id}/service-accounts": {
            "get": {
                "security": [
                    {
                        "SystemRole": []
                    },
                    {
                        "TenantID": []
                    },
                    {
                        "UserID": []
                    }
                ],
                "description": "Looks up a principal by its Keycloak sub rather than this service's own internal id (AUTH-9) — the signal another service needs to answer \"does this subject resolve to a service_account-typed Keycloak principal\" without ever generating principal_sub itself (TS-INV-1).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceAccounts"
                ],
                "summary": "TS-5 — Find service-account principal by Keycloak sub",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Keycloak sub UUID",
                        "name": "principal_sub",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.principalResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing_identity_headers",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "principal_not_found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SystemRole": []
                    },
                    {
                        "TenantID": []
                    },
                    {
                        "UserID": []
                    }
                ],
                "description": "Registers the per-tenant platform-automation service-account principal. Idempotent on (tenant_id, keycloak_client_id) — repeating an already-registered request returns 200 with the existing record instead of erroring.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceAccounts"
                ],
                "summary": "TS-4 — Register service-account principal",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Principal registration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.registerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "already registered — idempotent repeat",
                        "schema": {
                            "$ref": "#/definitions/http.principalResponseBody"
                        }
                    },
                    "201": {
                        "description": "created",
                        "schema": {
                            "$ref": "#/definitions/http.principalResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing_identity_headers",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "db_unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/{id}/service-accounts/platform-automation/jwks.json": {
            "get": {
                "description": "Public JWK Set for the tenant's platform-automation principal — the keys Keycloak's client-jwt authenticator fetches to verify that principal's client_assertion (§2.5). Always 200 with a (possibly empty) keys array; an unknown tenant or absent principal is never distinguished from a principal with zero live keys, since this route has no caller identity to authorize a 404 against.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceAccounts"
                ],
                "summary": "EXT-6 — Platform-automation JWKS",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.jwksResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "rate_limited",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/{id}/service-accounts/{principal_id}": {
            "get": {
                "security": [
                    {
                        "SystemRole": []
                    },
                    {
                        "TenantID": []
                    },
                    {
                        "UserID": []
                    }
                ],
                "description": "Returns principal metadata and a summary of every credential version (status, OpenBao path, issued/expires timestamps) — never the credential plaintext itself (§5.6).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceAccounts"
                ],
                "summary": "TS-3 — Read service-account principal",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Principal UUID",
                        "name": "principal_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.readPrincipalResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing_identity_headers",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "principal_not_found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/{id}/service-accounts/{principal_id}/credentials": {
            "post": {
                "security": [
                    {
                        "SystemRole": []
                    },
                    {
                        "TenantID": []
                    },
                    {
                        "UserID": []
                    }
                ],
                "description": "Issues the principal's first credential (version=1, 201) or rotates to a new version (201) when one already exists. A rotation_id replay of an already-committed request returns the stored result (200) instead of generating new material (§9.2). Returns a PEM-encoded RSA private key exactly once — it is never retrievable again (TS-INV-2); the matching public key is served at the principal's JWKS endpoint (EXT-6, §2.5) once RP-17 refreshes Keycloak's keys cache.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "TS-1 — Issue or rotate credential",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Principal UUID",
                        "name": "principal_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "rotation_id required; overlap_seconds optional (defaults to the configured value, §12)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.issueOrRotateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rotation_id replay — already committed",
                        "schema": {
                            "$ref": "#/definitions/http.issueOrRotateResponseBody"
                        }
                    },
                    "201": {
                        "description": "issued or rotated",
                        "schema": {
                            "$ref": "#/definitions/http.issueOrRotateResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing_identity_headers",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "principal_not_found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "rotation_in_flight OR optimistic_lock_conflict",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "principal_revoked",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "secret_store_unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenants/{id}/service-accounts/{principal_id}/credentials/{version}/revoke": {
            "post": {
                "security": [
                    {
                        "SystemRole": []
                    },
                    {
                        "TenantID": []
                    },
                    {
                        "UserID": []
                    }
                ],
                "description": "Revokes one credential version — deletes its OpenBao material and marks it revoked. keycloak_invalidation is always \"caller_responsibility\": this service never invalidates the token at Keycloak itself (two-halves invariant, TS-INV-7).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "TS-2 — Revoke credential version",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tenant UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Principal UUID",
                        "name": "principal_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Credential version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.revokeResponseBody"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing_identity_headers",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "principal_not_found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "optimistic_lock_conflict",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "secret_store_unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "error": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        },
        "http.credentialSummaryBody": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "issued_at": {
                    "type": "string"
                },
                "next_rotation_at": {
                    "type": "string"
                },
                "openbao_path": {
                    "type": "string"
                },
                "rotation_cadence_days": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "http.issueOrRotateRequestBody": {
            "type": "object",
            "properties": {
                "overlap_seconds": {
                    "type": "integer"
                },
                "rotation_id": {
                    "type": "string"
                }
            }
        },
        "http.issueOrRotateResponseBody": {
            "type": "object",
            "properties": {
                "expires_prior_at": {
                    "type": "string"
                },
                "openbao_path": {
                    "type": "string"
                },
                "record_version": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "http.jwksResponseBody": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                }
            }
        },
        "http.principalResponseBody": {
            "type": "object",
            "properties": {
                "principal_id": {
                    "type": "string"
                },
                "principal_type": {
                    "type": "string"
                },
                "record_version": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "http.readPrincipalResponseBody": {
            "type": "object",
            "properties": {
                "credentials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.credentialSummaryBody"
                    }
                },
                "keycloak_client_id": {
                    "type": "string"
                },
                "principal_id": {
                    "type": "string"
                },
                "principal_type": {
                    "type": "string"
                },
                "record_version": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "http.registerRequestBody": {
            "type": "object",
            "properties": {
                "keycloak_client_id": {
                    "type": "string"
                },
                "principal_sub": {
                    "type": "string"
                }
            }
        },
        "http.revokeResponseBody": {
            "type": "object",
            "properties": {
                "keycloak_invalidation": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "SystemRole": {
            "description": "Must contain \"iam-system\". Injected by the API gateway / mesh; never set by callers directly.",
            "type": "apiKey",
            "name": "x-tenant-roles",
            "in": "header"
        },
        "TenantID": {
            "description": "Tenant UUID injected by the API gateway. Must match the :id path segment (§5.1).",
            "type": "apiKey",
            "name": "x-tenant-id",
            "in": "header"
        },
        "UserID": {
            "description": "Caller identity injected by the API gateway — recorded as the actor on any mutation.",
            "type": "apiKey",
            "name": "x-user-id",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/internal",
	Schemes:          []string{},
	Title:            "IAM Token Service API",
	Description:      "Token Service microservice — custodian of the platform-automation service account's rotating credential material (issue, rotate, revoke; TS-1..TS-4).\n\n**Tenant isolation:** All resource access is strictly scoped by x-tenant-id. Cross-tenant access is never permitted (RLS-6).\n**Secret handling:** The generated credential plaintext is returned exactly once, on TS-1's response body, and never logged, traced, or echoed again (TS-INV-2).\n**No Keycloak dependency:** This service manages its own credential material independently — it never calls the Keycloak Admin API (TS-INV-1).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
