#!/usr/bin/env python3
"""Render docs/observability/metric-registry.md: every metric this service
emits, from two sources of truth.

  * The Platform Observability Registry shipped with the pinned
    platform-gincommon (internal/obsregistry/registry.json): every Tier 1
    metric owned by a platform library this service links (platform-gincommon
    HTTP server, platform-events, platform-pgcommon), and the Tier 2 iam_*
    entries.
  * A real /metrics scrape (test/unit/metricsstandard's
    TestStandard_LibrariesShareRegistryCollectors, which records one sample
    on every collector this service owns): the
    Tier 2 metrics actually emitted (none today) and every Tier 3
    iam_token_service_* metric with its type, labels and help text.

Usage: metrics-inventory.py <registry.json> <scrape.txt> <gincommon-version>
Writes the Markdown to stdout. Run through `make metrics-inventory`; CI
fails when the committed file differs (.github/scripts/metricslint.sh).
"""
import json
import re
import sys

LIBRARIES = ("platform-gincommon", "platform-events", "platform-pgcommon")
# Series-level labels that are not part of a metric's own label set.
IGNORED_LABELS = {"domain", "service", "environment", "le", "quantile"}
SERVICE = "iam-token-service"
SERVICE_PREFIX = "iam_token_service_"


def md(text):
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def parse_scrape(path):
    """Return {family: {"type", "help", "labels"}} from Prometheus text."""
    families = {}
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("# HELP "):
            name, _, help_text = line[len("# HELP "):].partition(" ")
            families.setdefault(name, {"labels": set()})["help"] = help_text
        elif line.startswith("# TYPE "):
            name, _, mtype = line[len("# TYPE "):].partition(" ")
            families.setdefault(name, {"labels": set()})["type"] = mtype
        elif line and not line.startswith("#"):
            m = re.match(r"([a-zA-Z_:][a-zA-Z0-9_:]*)(\{([^}]*)\})?", line)
            if not m:
                continue
            series = m.group(1)
            family = series
            for suffix in ("_bucket", "_sum", "_count"):
                if series.endswith(suffix) and series[: -len(suffix)] in families:
                    family = series[: -len(suffix)]
            labels = re.findall(r'([a-zA-Z_][a-zA-Z0-9_]*)="', m.group(3) or "")
            families.setdefault(family, {"labels": set()})["labels"].update(
                label for label in labels if label not in IGNORED_LABELS
            )
    return families


def labels_cell(entry):
    labels = entry.get("labels") or []
    if not labels:
        return "-"
    cell = ", ".join(f"`{label}`" for label in labels)
    for label, values in sorted((entry.get("label_values") or {}).items()):
        cell += f"<br>`{label}` ∈ " + ", ".join(f"`{v}`" for v in values)
    return cell


def type_cell(entry):
    mtype = entry.get("type", "")
    if mtype == "histogram" and entry.get("buckets"):
        return f"histogram ({entry['buckets']})"
    return mtype


def main():
    registry_path, scrape_path, gincommon_version = sys.argv[1:4]
    registry = json.load(open(registry_path, encoding="utf-8"))
    scrape = parse_scrape(scrape_path)
    entries = registry["metrics"]

    out = []
    w = out.append
    w(f"# Metric inventory: {SERVICE}")
    w("")
    w("<!-- Generated by `make metrics-inventory` (.github/scripts/metrics-inventory.py) from the")
    w(f"     Platform Observability Registry in platform-gincommon {gincommon_version} and a real /metrics")
    w("     scrape of this service. Do not edit; CI fails when this file is out of date. -->")
    w("")
    w("Every series carries the centrally injected const labels `domain` (`iam`), `service` "
      f"(`{SERVICE}`) and `environment`. "
      "The four binaries (`cmd/server`, `cmd/consumer`, `cmd/rotator`, `cmd/scheduler`) "
      "register the same set and share this identity. The tables list each metric's own labels only. "
      "Status is the registry's: `approved`, or `proposed` (awaiting observability-governance "
      "ratification). Tier 3 metrics are this service's own and need no registry entry. "
      "See [README.md](README.md) for how the tiers are built and enforced.")
    w("")

    w("## Tier 1: platform-shared metrics (emitted by the platform libraries)")
    w("")
    w("This service does not construct these. The libraries record them on the shared "
      "registry (`gincommon.MetricsRegisterer()`). The service records into two of them "
      "(`platform_dependency_request_seconds{dependency=\"openbao\"}`, "
      "`platform_duplicate_messages_total`) by adopting platform-events' collector "
      "(`registerShared` in `internal/adapter/outbound/metrics/metrics.go`).")
    w("")
    w("| Metric | Emitted by | Type | Status | Labels | Meaning |")
    w("|---|---|---|---|---|---|")
    for entry in entries:
        if entry.get("tier") != "platform" or entry.get("owner") not in LIBRARIES:
            continue
        if entry["name"].startswith("platform_grpc_"):
            continue  # no gRPC server in this service
        w(f"| `{entry['name']}` | {entry['owner']} | {type_cell(entry)} | {entry.get('status', '')} "
          f"| {labels_cell(entry)} | {md(entry.get('help'))} |")
    w("")

    w("## Tier 2: IAM domain-shared metrics (emitted by this service)")
    w("")
    emitted_domain = [e for e in entries if e.get("tier") == "domain" and e["name"] in scrape]
    if emitted_domain:
        w("Built from the registry entry (name, help and labels) in `registerMetrics` "
          "(`internal/adapter/outbound/metrics/metrics.go`). `iam_rls_violations_total` is "
          "counted by `cmd/server`'s exporter from `rls_violation_log` (migration 000003).")
        w("")
        w("| Metric | Type | Status | Labels | Meaning |")
        w("|---|---|---|---|---|")
    else:
        w("None. An `iam_*` name must be a Platform Observability Registry entry before any "
          "service emits it; this service's candidate (`iam_offboarding_cascade_total`, "
          "Proposal 3 in [`../observability-registry-proposals.md`](../observability-registry-proposals.md)) "
          "is withheld until ratified.")
    for entry in emitted_domain:
        w(f"| `{entry['name']}` | {type_cell(entry)} | {entry.get('status', '')} "
          f"| {labels_cell(entry)} | {md(entry.get('help'))} |")
    w("")
    others = [e["name"] for e in entries if e.get("tier") == "domain" and e["name"] not in scrape]
    if others:
        w("Registered for the `iam` domain but not emitted by this service: "
          + ", ".join(f"`{name}`" for name in others) + ".")
        w("")

    w(f"## Tier 3: service-specific metrics (`{SERVICE_PREFIX}*`)")
    w("")
    w("| Metric | Type | Labels | Meaning |")
    w("|---|---|---|---|")
    for name in sorted(n for n in scrape if n.startswith(SERVICE_PREFIX)):
        fam = scrape[name]
        labels = ", ".join(f"`{label}`" for label in sorted(fam["labels"])) or "-"
        w(f"| `{name}` | {fam.get('type', '')} | {labels} | {md(fam.get('help'))} |")
    w("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
