// Package main is the composition root for the Token Service's HTTP API
// process (§5): the 7 internal routes — TS-1..TS-6 plus EXT-6's public
// JWKS route — and the outbox runner that publishes every process's
// enqueued events. cmd/consumer (the offboarding cascade, §8.4),
// cmd/rotator (overlap-expiry sweep, orphan-material reconciler, retention
// prune, §8.3/§8.6) and cmd/scheduler (cadence rotation, TS-D14) are the
// other three entrypoints built from the same image.
package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"sync/atomic"
	"syscall"
	"time"

	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/glue"
	"github.com/gin-gonic/gin"

	// docs/swagger is generated by `make swag` from this package's and
	// internal/adapter/inbound/http's swaggo annotations — its init()
	// registers the spec with swaggo's global registry, which
	// ginSwagger.WrapHandler (router.go) reads from.
	_ "github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/docs/swagger"
	httpadapter "github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/adapter/inbound/http"
	eventbusadapter "github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/adapter/outbound/eventbus"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/adapter/outbound/metrics"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/adapter/outbound/openbao"
	pgadapter "github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/adapter/outbound/postgres"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/core/domain"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/iam-token-service/internal/core/service"

	"github.com/BCBP-SOLUTIONS-FZC-LLC/platform-gincommon/pkg/gincommon"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/platform-gincommon/pkg/logger"
	"github.com/BCBP-SOLUTIONS-FZC-LLC/platform-pgcommon/v2/pkg/pgcommon"
)

// buildVersion is injected by -ldflags at build time (see Dockerfile / Makefile).
var buildVersion = "dev"

func main() {
	appEnv := envOr("APP_ENV", "dev")
	if appEnv != "dev" {
		gin.SetMode(gin.ReleaseMode)
	}

	// ── 1. Logger — Zap via platform-gincommon (same sink as iam-org-membership)
	log, err := logger.NewLogger(appEnv)
	if err != nil {
		panic("init logger: " + err.Error())
	}

	cfg := gincommon.Config{
		Logger:       log,
		ServiceName:  envOr("APP_NAME", "iam-token-service"),
		BuildVersion: envOr("BUILD_VERSION", buildVersion),
		// Observability identity (Enterprise Platform Observability
		// Standard): domain "iam" (OBSERVABILITY_DOMAIN overrides it) and the
		// environment label, which must be one of local/dev/test/staging/prod
		// — ObservabilityMiddlewares panics on anything else (e.g. "production").
		Domain:      envOr("OBSERVABILITY_DOMAIN", metrics.ObservabilityDomain),
		Environment: appEnv,
		// RequestTimeout appends gincommon's TimeoutMiddleware as the
		// innermost observability handler, so metrics, the access log and the
		// server span record the same 503 the client receives. As an outer
		// r.Use it ran before observability, which recorded 200.
		RequestTimeout: 30 * time.Second,
	}

	// Tracing with the SAME identity as metrics (service, version, domain,
	// environment) — InitTracingFromEnv read OTEL_SERVICE_NAME and the
	// domain/environment from the environment on its own, so traces could
	// disagree with metrics. Always installs gincommon's TracerProvider so
	// in-process spans get valid trace IDs even with no OTLP endpoint (dev);
	// ObservabilityMiddlewares' EnsureInitTelemetry is then a no-op.
	shutdownTracing, err := gincommon.InitTracingWithConfig(gincommon.TracingConfig{
		ServiceName:  cfg.ServiceName,
		BuildVersion: cfg.BuildVersion,
		Domain:       cfg.Domain,
		Environment:  cfg.Environment,
		Logger:       log,
	})
	if err != nil {
		panic("init tracing: " + err.Error())
	}
	// ObservabilityMiddlewares is gincommon's public metrics-init API. Call
	// it here (before any collector registration) so business metrics land
	// on gincommon.MetricsRegisterer with matching {domain, service, environment} const
	// labels. NewRouter applies the same middleware slice to the engine.
	_ = gincommon.ObservabilityMiddlewares(cfg)
	// platform-events' (outbox/publish/consume/SQS/SNS) and platform-pgcommon's
	// (platform_db_*) metrics share gincommon's registerer and identity so one
	// /metrics scrape serves HTTP + business + messaging + DB collectors. Must
	// run before NewPool (pool gauges are registered by NewPool) and before
	// metrics.Register (which records into platform-events' shared collectors).
	if err := metrics.InitLibraryMetrics(log); err != nil {
		panic(fmt.Sprintf("init library metrics: %v", err))
	}
	metrics.Register(appEnv) // Tier 1/2/3 business metrics (Enterprise Platform Observability Standard)

	// ── 3. Database — pgcommon.ConfigFromEnv reads DATABASE_URL/PG_* so
	// pool sizing, PgBouncer mode, and DSN assembly have exactly one
	// implementation (§4, §12). ──────────────────────────────────────────
	pgCfg, pgWarnings := pgcommon.ConfigFromEnv()
	for _, w := range pgWarnings {
		log.Warn("postgres config warning", map[string]interface{}{"key": w.Key, "reason": w.Reason})
	}
	dsn := pgadapter.DSNFromEnv()
	// Migrations must bypass PgBouncer — the migration runner acquires a
	// pg_advisory_lock, which is session-scoped and breaks under
	// transaction pooling (§4.4/TS-CONFIG-2).
	migrationDSN := pgadapter.MigrationDSNFromEnv()

	pgCfg.DSN = dsn
	pgCfg.GUCProvider = pgcommon.GUCSetFromContext
	pgCfg.Logger = pgadapter.NewLoggerAdapter(log)
	// db.query spans export through the TracerProvider
	// gincommon.InitTracingWithConfig installed above — same OTLP pipeline as
	// HTTP spans from ObservabilityMiddlewares.
	pgCfg.Tracer = gincommon.NewSpanTracer(cfg.ServiceName)
	pool, err := pgcommon.NewPool(context.Background(), pgCfg)
	if err != nil {
		panic(fmt.Sprintf("connect to postgres: %v", err))
	}
	defer pool.Close()

	ctx, cancelBackground := context.WithCancel(context.Background())
	defer cancelBackground()

	// Migrations (§4.4/MIG-2 order inside pgadapter.Migrate). In Kubernetes
	// they run once per release in the Helm migrate Job (this binary with
	// MIGRATE_ONLY=true) and every workload sets RUN_MIGRATIONS=false.
	if pgadapter.MigrateOnlyFromEnv() {
		if err := pgadapter.Migrate(ctx, migrationDSN, log); err != nil {
			panic(fmt.Sprintf("migrate: %v", err))
		}
		log.Info("migrations applied (MIGRATE_ONLY) — exiting", nil)
		return
	}
	if pgadapter.MigrationsEnabledFromEnv() {
		if err := pgadapter.Migrate(ctx, migrationDSN, log); err != nil {
			panic(fmt.Sprintf("migrate: %v", err))
		}
	}

	// ── 4. OpenBao KV v2 secret store (§6.3, §10.5) ──────────────────────
	openbaoClient, err := openbao.New(openbao.Config{
		Addr:     mustEnv("OPENBAO_ADDR", appEnv, "https://openbao.iam.svc.cluster.local:8200"),
		AuthRole: envOr("OPENBAO_ROLE", "iam-token-service"),
		KVMount:  envOr("OPENBAO_KV_MOUNT", "iam"),
		// Empty = the default ServiceAccount token path; Helm sets it to an
		// OpenBao-audience projected token (openbao.tokenAudience).
		KubernetesTokenPath: os.Getenv("OPENBAO_K8S_TOKEN_PATH"),
	}, log)
	if err != nil {
		panic(fmt.Sprintf("init openbao client: %v", err))
	}
	instrumentedSecrets := metrics.NewInstrumentedSecretStore(openbaoClient) // iam_token_service_openbao_call_duration_seconds

	// reconcilerPool: read-only BYPASSRLS pool (§4.3/RLS-7), used ONLY by
	// the rotation-overlap gauge exporter below — the write path (TS-1..4)
	// never touches this pool.
	//
	// Built via SystemPoolConfig (same helper as iam-user-profile /
	// iam-org-membership): no GUCProvider, PGBouncerMode forced true, pool
	// sizing inherited from ConfigFromEnv. Tracer is wired separately so
	// db.query spans export through gincommon's TracerProvider.
	reconDSN := pgadapter.ReconcilerDSNFromEnv()
	reconCfg := pgadapter.SystemPoolConfig(reconDSN, log)
	reconCfg.Tracer = gincommon.NewSpanTracer(cfg.ServiceName)
	reconcilerPool, err := pgcommon.NewPool(context.Background(), reconCfg)
	if err != nil {
		panic(fmt.Sprintf("connect reconciler pool: %v", err))
	}
	defer reconcilerPool.Close()
	if reconDSN == dsn {
		log.Warn("RECONCILER_DATABASE_URL not set — reconciler pool reuses app DSN; cross-tenant queries will be RLS-filtered", nil)
	}

	// ── 5. AWS clients (Glue Schema Registry, SNS — §7.3.1) ──────────────
	awsCfg, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion(envOr("AWS_REGION", "ap-south-1")))
	if err != nil {
		panic(fmt.Sprintf("load aws config: %v", err))
	}
	var glueOpts []func(*glue.Options)
	if ep := os.Getenv("AWS_ENDPOINT_URL"); ep != "" {
		glueOpts = append(glueOpts, func(o *glue.Options) { o.BaseEndpoint = &ep })
	}
	glueClient := glue.NewFromConfig(awsCfg, glueOpts...)

	// ── 6. Repositories + TxRunner ────────────────────────────────────────
	principalRepo := pgadapter.NewPrincipalRepository(pool)
	credentialRepo := pgadapter.NewCredentialRepository(pool)

	// Enqueue-time codec: schema-shape validation only (NoopCodec — no wire
	// encoding at enqueue time, §7.3.1). Glue wire encoding happens only at
	// SNS-publish time, via the outbox runner's Publisher below.
	enqueueCodec, err := eventbusadapter.NewValidatingCodec(eventbusadapter.NoopCodec{})
	if err != nil {
		panic(fmt.Sprintf("init validating codec: %v", err))
	}
	outboxPublisher := eventbusadapter.New(cfg.ServiceName, enqueueCodec).WithLogger(log)
	txRunner := pgadapter.NewTxRunner(pool, outboxPublisher)

	// ── 7. Core services ──────────────────────────────────────────────────
	credentialSvc := service.NewCredentialService(principalRepo, credentialRepo, instrumentedSecrets, txRunner, log, nil).
		WithCadenceDays(envInt("ROTATION_DEFAULT_CADENCE_DAYS", domain.DefaultCadenceDays)).
		WithReplayWindow(replayWindowFromEnv())
	principalSvc := service.NewPrincipalService(principalRepo, credentialRepo, txRunner)
	instrumentedCredentialSvc := metrics.NewInstrumentedCredentialService(credentialSvc) // iam_token_service_credentials_issued_total
	jwksSvc := service.NewJWKSService(principalRepo, credentialRepo, instrumentedSecrets, log)

	// ── 8. Glue codec + SNS publisher + outbox runner (§7.3.1, §7.4) ──────
	// Both GLUE_REGISTRY_NAME and SNS_TOPIC_ARN are read
	// with no code-level default and no dev placeholder: empty means
	// dev/test without real AWS, and buildGlueCodec/buildSNSPublisher fall
	// back to NoopCodec/a no-op publisher rather than eagerly hitting AWS
	// and crashing the pod at startup. validateRequiredEnv below enforces
	// that they ARE set outside dev (§12.1 fail-fast) — the frozen
	// registry/topic values (§25) are supplied via env in real deployments,
	// never hardcoded in this binary (TS-CONFIG-1).
	validateRequiredEnv(appEnv)

	producedSchemas, err := eventbusadapter.ProducedSchemas()
	if err != nil {
		panic(fmt.Sprintf("load produced event schemas: %v", err))
	}
	schemaNames := make([]string, 0, len(producedSchemas))
	for name := range producedSchemas {
		schemaNames = append(schemaNames, name)
	}
	glueCodec, err := buildGlueCodec(ctx, glueClient, os.Getenv("GLUE_REGISTRY_NAME"), schemaNames)
	if err != nil {
		panic(fmt.Sprintf("init glue codec: %v", err))
	}
	snsPublisher, err := buildSNSPublisher(glueCodec, log)
	if err != nil {
		panic(fmt.Sprintf("build sns publisher: %v", err))
	}

	outboxRunner, err := newOutboxRunner(pool, snsPublisher, log)
	if err != nil {
		panic(fmt.Sprintf("create outbox runner: %v", err))
	}
	go func() {
		if err := outboxRunner.Start(ctx); err != nil {
			log.Error("outbox runner stopped", map[string]interface{}{"error": err.Error()})
		}
	}()

	// iam_token_service_rotation_overlap_active gauge exporter (§11.2) — a
	// DB-state gauge no request/reconciler path can maintain, refreshed
	// here from the BYPASSRLS reconciler pool, matching the sibling
	// exporter-goroutine pattern.
	go runRotationOverlapExporter(ctx, reconcilerPool, envDuration("ROTATION_OVERLAP_GAUGE_INTERVAL", 30*time.Second), log)
	// iam_rls_violations_total (Tier 2) from rls_violation_log — readable
	// only by the reconciler role, so it uses the same pool.
	go runRLSViolationExporter(ctx, pgadapter.NewRLSViolationRepository(reconcilerPool), envDuration("RLS_VIOLATION_EXPORTER_INTERVAL", time.Minute), log)
	// iam_token_service_keys_refresh_pending / _oldest_age_seconds — owed
	// RP-17 refreshes recorded by cmd/rotator and cmd/scheduler, counted
	// cross-tenant, so PendingStats reads over the reconciler pool.
	go runKeysRefreshPendingExporter(ctx, pgadapter.NewKeysRefreshRepository(pool, reconcilerPool), envDuration("KEYS_REFRESH_EXPORTER_INTERVAL", 30*time.Second), log)

	// JWKS known-tenant set: refreshed from the database (every tenant with
	// an active|rotating credential) so a freshly restarted or scaled-out
	// replica rate-limits a real tenant's first Keycloak fetch under the
	// global (plus per-tenant) bucket instead of the much tighter
	// unknown-tenant one. The
	// listing is cross-tenant, hence the BYPASSRLS reconciler pool (which,
	// like the exporters above, falls back to the app DSN in dev). Parsed
	// before the goroutine so a bad value fails startup, not silently 15s.
	jwksKnownTenantsRefresh := jwksKnownTenantsRefreshFromEnv()
	jwksHandler := httpadapter.NewJWKSHandler(jwksSvc).
		WithLogger(log). // otherwise a failing known-tenant refresh is silent
		WithRateLimit(envFloat("JWKS_RATE_LIMIT_RPS", 20), envInt("JWKS_RATE_LIMIT_BURST", 40)).
		WithPerTenantRateLimit(envFloat("JWKS_RATE_LIMIT_PER_TENANT_RPS", 5), envInt("JWKS_RATE_LIMIT_PER_TENANT_BURST", 10)).
		WithUnknownTenantRateLimit(envFloat("JWKS_RATE_LIMIT_UNKNOWN_TENANT_RPS", 2), envInt("JWKS_RATE_LIMIT_UNKNOWN_TENANT_BURST", 5))
	go jwksHandler.RunKnownTenantRefresher(ctx, pgadapter.NewJWKSTenantsRepository(reconcilerPool), jwksKnownTenantsRefresh)

	// ── 9. Router ─────────────────────────────────────────────────────────
	router := httpadapter.NewRouter(httpadapter.RouterConfig{
		GinConfig: cfg,
		Docs: httpadapter.DocsConfig{
			Environment: appEnv,
			Enabled:     envOr("DOCS_ENABLED", "false") == "true",
			AuthToken:   os.Getenv("DOCS_AUTH_TOKEN"),
		},
		Handlers: httpadapter.Handlers{
			Principal: httpadapter.NewPrincipalHandler(principalSvc),
			Credential: httpadapter.NewCredentialHandler(instrumentedCredentialSvc).
				WithDefaultOverlapSeconds(defaultOverlapSecondsFromEnv()),
			JWKS: jwksHandler,
		},
		// Every readiness check carries its own server-side deadline: the
		// probe's client-side timeout only abandons the request, it never
		// cancels a hung Postgres/OpenBao call, so without one stuck checks
		// pile up a goroutine per probe period.
		Postgres: withDeadline(readinessCheckTimeout, drainAwarePinger(&draining, func(ctx context.Context) error {
			if hs := pool.Health(ctx); !hs.Healthy {
				return fmt.Errorf("database not healthy")
			}
			return nil
		})),
		OpenBao: withDeadline(readinessCheckTimeout, openbaoClient.Health),
		Outbox: withDeadline(readinessCheckTimeout, func(context.Context) error {
			select {
			case <-outboxRunner.Ready():
				return nil
			default:
				return fmt.Errorf("outbox initializing")
			}
		}),
	})

	// ── 10. Graceful shutdown ─────────────────────────────────────────────
	srv := &http.Server{
		Addr:         ":" + envOr("APP_PORT", "8080"),
		Handler:      router.Handler(),
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 35 * time.Second,
		IdleTimeout:  60 * time.Second,
	}
	metricsMux := http.NewServeMux()
	metricsMux.Handle("/metrics", gincommon.MetricsHandler())
	metricsServer := &http.Server{
		Addr:              ":" + envOr("METRICS_PORT", "9090"),
		Handler:           metricsMux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	log.Info("service starting", map[string]interface{}{
		"service": cfg.ServiceName, "version": cfg.BuildVersion, "env": appEnv, "addr": srv.Addr,
	})
	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Error("server error", map[string]interface{}{"error": err.Error()})
		}
	}()
	go func() {
		log.Info("metrics server starting", map[string]interface{}{"addr": metricsServer.Addr})
		if err := metricsServer.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Error("metrics server error", map[string]interface{}{"error": err.Error()})
		}
	}()

	<-quit
	drainDelay := envDuration("SHUTDOWN_DRAIN_DELAY", 5*time.Second)
	log.Info("shutdown signal received — draining", map[string]interface{}{"drain_delay": drainDelay.String()})
	drainThenWait(&draining, drainDelay, time.Sleep)

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Error("HTTP server shutdown error", map[string]interface{}{"error": err.Error()})
	}
	if err := metricsServer.Shutdown(shutdownCtx); err != nil {
		log.Error("metrics server shutdown error", map[string]interface{}{"error": err.Error()})
	}
	if err := outboxRunner.Stop(); err != nil {
		log.Error("outbox runner drain error", map[string]interface{}{"error": err.Error()})
	}
	cancelBackground()
	// DrainAndClose waits for in-flight WithConn/RunInTx callbacks then
	// force-closes — pgcommon's documented graceful path. defer Close()
	// above remains a safety net for panic/early-return and is idempotent
	// after DrainAndClose returns (must not run concurrently).
	if err := pool.DrainAndClose(shutdownCtx); err != nil {
		log.Error("app pool drain error", map[string]interface{}{"error": err.Error()})
	}
	if err := reconcilerPool.DrainAndClose(shutdownCtx); err != nil {
		log.Error("reconciler pool drain error", map[string]interface{}{"error": err.Error()})
	}
	shutdownTracing()
	if err := gincommon.Shutdown(log); err != nil {
		log.Error("logger/tracer flush error", map[string]interface{}{"error": err.Error()})
	}
}

// draining is set on SIGTERM; /readyz fails while it is.
var draining atomic.Bool

var errDraining = errors.New("shutting down")

// pingerFunc adapts a plain func to httpadapter.Pinger.
type pingerFunc func(context.Context) error

func (f pingerFunc) Health(ctx context.Context) error { return f(ctx) }

// drainAwarePinger reports errDraining once draining is set, before
// consulting next — so /readyz turns 503 the moment SIGTERM lands and the
// endpoint is pulled before the listener closes, even while the database
// itself is still perfectly healthy.
func drainAwarePinger(draining *atomic.Bool, next pingerFunc) pingerFunc {
	return func(ctx context.Context) error {
		if draining.Load() {
			return errDraining
		}
		return next(ctx)
	}
}

// readinessCheckTimeout bounds each /readyz dependency check. It sits below
// the readinessProbe's timeoutSeconds (3, Helm) so the handler always
// answers 503 itself rather than letting the kubelet time the probe out.
const readinessCheckTimeout = 2 * time.Second

// withDeadline runs next under a context that expires after timeout.
func withDeadline(timeout time.Duration, next pingerFunc) pingerFunc {
	return func(ctx context.Context) error {
		ctx, cancel := context.WithTimeout(ctx, timeout)
		defer cancel()
		return next(ctx)
	}
}

// drainThenWait flips readiness to 503 and only THEN waits delay: the
// listener stays open for SHUTDOWN_DRAIN_DELAY while the endpoint removal
// propagates to every caller (kube-proxy, mesh, Keycloak's JWKS fetch), so
// in-flight routing still lands on an open socket instead of
// connection-refused. Setting the flag after the sleep would keep the pod
// Ready for the whole delay and defeat the point. sleep is injected so a
// test can observe the flag at the moment the wait starts.
func drainThenWait(draining *atomic.Bool, delay time.Duration, sleep func(time.Duration)) {
	draining.Store(true)
	sleep(delay)
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envInt(key string, def int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			return n
		}
	}
	return def
}

func envFloat(key string, def float64) float64 {
	if v := os.Getenv(key); v != "" {
		if f, err := strconv.ParseFloat(v, 64); err == nil && f > 0 {
			return f
		}
	}
	return def
}

func envDuration(key string, def time.Duration) time.Duration {
	if v := os.Getenv(key); v != "" {
		if d, err := time.ParseDuration(v); err == nil && d > 0 {
			return d
		}
	}
	return def
}

// isDevEnv reports whether appEnv is one of the local/CI-only values that
// permit a hard dependency's safe placeholder default (§12.1 fail-fast).
func isDevEnv(appEnv string) bool {
	return appEnv == "dev" || appEnv == "development" || appEnv == "local" || appEnv == "test"
}

// mustEnv panics with a descriptive message if key is empty outside a dev
// APP_ENV; dev falls back to devDefault so a bare-metal `go run` works with
// no .env at all (§12.1 fail-fast).
func mustEnv(key, appEnv, devDefault string) string {
	v := os.Getenv(key)
	if v != "" {
		return v
	}
	if isDevEnv(appEnv) {
		return devDefault
	}
	panic(fmt.Sprintf("startup aborted — required env var %s is not set", key))
}

// validateRequiredEnv panics with every missing env var listed at once
// (fail-fast, §12.1) — an empty GLUE_REGISTRY_NAME or
// SNS_TOPIC_ARN outside dev would otherwise start the
// service with the outbox silently queuing events that are never
// published, rather than failing loudly at boot.
func validateRequiredEnv(appEnv string) {
	// Checked before the dev early-return: isDevEnv also accepts the legacy
	// "development", which DocsConfig treats as restricted (it knows only
	// local/dev/test), so skipping this there would serve docs without auth.
	if docsUnprotected(appEnv) {
		panic("startup aborted — required env vars missing:\n  • DOCS_AUTH_TOKEN: DOCS_ENABLED=true in APP_ENV=" + appEnv + " (any environment other than local/dev/test) would expose the Swagger/AsyncAPI docs unauthenticated; set Helm value docs.authEnabled=true (DOCS_AUTH_TOKEN from the secret) or docs.enabled=false\n")
	}
	if isDevEnv(appEnv) {
		return
	}
	type req struct{ key, reason string }
	reqs := []req{
		{"GLUE_REGISTRY_NAME", "AWS Glue Schema Registry name for iam.serviceaccount.events (§25, frozen value 'iam-serviceaccount-events'); set Helm value events.glueRegistryName"},
		{"SNS_TOPIC_ARN", "iam-serviceaccount-events SNS topic ARN; events would queue in the outbox but never publish without it; set Helm value events.topicArn"},
	}
	var missing []string
	for _, r := range reqs {
		if os.Getenv(r.key) == "" {
			missing = append(missing, r.key+": "+r.reason)
		}
	}
	if len(missing) > 0 {
		msg := "startup aborted — required env vars missing:\n"
		for _, m := range missing {
			msg += "  • " + m + "\n"
		}
		panic(msg)
	}
}

// docsUnprotected reports whether the docs surfaces would be served outside
// a developer environment with no bearer token. DocsConfig treats every
// APP_ENV other than local/dev/test like prod (staging included):
// mounted only when DOCS_ENABLED=true, and an empty DOCS_AUTH_TOKEN then
// means the full internal API surface published to anyone who can reach
// the port. That is a misconfiguration, never an intent, so it fails
// startup. The dev set is deliberately the closed local/dev/test list, not
// isDevEnv: an unrecognised value must land on the strict side.
func docsUnprotected(appEnv string) bool {
	switch strings.ToLower(strings.TrimSpace(appEnv)) {
	case "local", "dev", "test":
		return false
	}
	return envOr("DOCS_ENABLED", "false") == "true" && strings.TrimSpace(os.Getenv("DOCS_AUTH_TOKEN")) == ""
}

// jwksKnownTenantsRefreshFromEnv reads JWKS_KNOWN_TENANTS_REFRESH (a Go
// duration, default 15s) — how often the JWKS handler reloads its
// known-tenant set from the database. Unlike envDuration it fails startup
// on a non-positive or unparseable value: time.NewTicker panics on <= 0,
// and silently falling back would hide the typo.
func jwksKnownTenantsRefreshFromEnv() time.Duration {
	raw := strings.TrimSpace(os.Getenv("JWKS_KNOWN_TENANTS_REFRESH"))
	if raw == "" {
		return 15 * time.Second
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d <= 0 {
		panic(fmt.Sprintf("startup aborted — JWKS_KNOWN_TENANTS_REFRESH=%q must be a positive Go duration (e.g. 15s)", raw))
	}
	return d
}

// replayWindowFromEnv reads ROTATION_REPLAY_WINDOW (a Go duration; "0"
// lifts the limit; unset is service.DefaultReplayWindow, 15m) — how long
// after issue a TS-1 retry carrying the same rotation_id may still replay
// the private key. Unlike envDuration it does not fall back silently: 0 is
// a meaningful value, and a negative or unparseable one is a
// misconfiguration that must fail startup rather than quietly become 15m.
func replayWindowFromEnv() time.Duration {
	raw := strings.TrimSpace(os.Getenv("ROTATION_REPLAY_WINDOW"))
	if raw == "" {
		return service.DefaultReplayWindow
	}
	if raw == "0" {
		return 0
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d < 0 {
		panic(fmt.Sprintf("startup aborted — ROTATION_REPLAY_WINDOW=%q must be a non-negative Go duration (e.g. 15m; 0 disables the limit)", raw))
	}
	return d
}

// defaultOverlapSecondsFromEnv reads ROTATION_DEFAULT_OVERLAP_SECONDS (the
// overlap applied when TS-1 omits overlap_seconds, §12) and fails startup
// when it is outside [0, 900] (TS-CONFIG-4) instead of silently clamping a
// misconfiguration.
func defaultOverlapSecondsFromEnv() int {
	raw := strings.TrimSpace(os.Getenv("ROTATION_DEFAULT_OVERLAP_SECONDS"))
	if raw == "" {
		return domain.DefaultOverlapSeconds
	}
	// Parsed here rather than with envInt, which ignores 0 and bad values:
	// 0 is a legitimate hard cutover (§6.2), and anything unparseable or out
	// of range must fail startup, not silently become 300.
	v, err := strconv.Atoi(raw)
	if err != nil || v < domain.MinOverlapSeconds || v > domain.MaxOverlapSeconds {
		panic(fmt.Sprintf("startup aborted — ROTATION_DEFAULT_OVERLAP_SECONDS=%q must be an integer in [%d, %d] (TS-CONFIG-4)",
			raw, domain.MinOverlapSeconds, domain.MaxOverlapSeconds))
	}
	return v
}
